/*
   Copyright 2026 Samo Pogačnik

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
{
  description = "A flake to build yx environments";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
  };

  outputs = { self, nixpkgs }: let
    system = "x86_64-linux"; # Containers must be built for Linux
    pkgs = nixpkgs.legacyPackages.${system};
    lib = pkgs.lib;
    # Create a custom etc/oe-release file for the yx environment:
    osRelease = pkgs.writeTextDir "etc/os-release" ''
      PRETTY_NAME="Why-Ex Environment"
      NAME="yx-env"
      ID="yxenv"
      VERSION_ID="0.0.1"
    '';
    fakeSudo = pkgs.writeScriptBin "sudo" ''
    #!/bin/sh
    exec "$@"
    '';
    lz4C = pkgs.writeScriptBin "lz4c" ''
    #!/bin/sh
    exec "lz4 $@"
    '';

    # This wrapper fixes the "one giant filename" issue
    rpcgen-wrapper = pkgs.writeShellScriptBin "rpcgen" ''
      # CPP often looks like "gcc -E --sysroot=..."
      # which breaks rpcgen!
      if [ -n "$CPP" ]; then
        # Redefine CPP:
        CPP=$(echo $CPP | awk '{print $1}' | sed 's/gcc/cpp/')
      fi
      exec ${pkgs.rpcsvc-proto}/bin/rpcgen "$@"
    '';

    sharedPkgs = import ./packages.nix { inherit pkgs; } ++ [ fakeSudo lz4C (lib.hiPrio rpcgen-wrapper) osRelease ];

    # Example: Creating a basic FHS shell
    fhs = pkgs.buildFHSEnv {
      name = "yx-env-fhs";
      targetPkgs = pkgs: sharedPkgs ++ [
        # 1. Create a Python environment that includes the missing module
        (pkgs.python3.withPackages (ps: with ps; [
          argcomplete
          # add other modules here
        ]))
      ];

      # 2. This script runs when the shell (or nix develop) starts
      profile = ''
        export TZDIR=/share/zoneinfo
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US:en
        export LC_ALL=en_US.UTF-8
        export LOCALE_ARCHIVE=/lib/locale/locale-archive
        export BB_ENV_PASSTHROUGH_ADDITIONS="\$BB_ENV_PASSTHROUGH_ADDITIONS LOCALE_ARCHIVE"
      '';

      runScript = "bash";
    };

    # 1. Define the "FHS-like" environment
    fhsLayout = pkgs.buildEnv {
      name = "yx-env-root-layout";
      # List all packages you want in the standard paths
      paths = sharedPkgs;
      # 2. Tell Nix which folders to symlink to the root
      pathsToLink = [ "/bin" "/etc" "/include" "/lib" "/share" "/usr" "/var" ];
      # Either package priority or this (see glibc.dev in packages.nix)
      #ignoreCollisions = true;
    };

    # Create a wrapper that moves /include to /usr/include
    usrInclude = pkgs.runCommand "usr-include" {} ''
      mkdir -p $out/usr
      ln -s ${fhsLayout}/include $out/usr/include
    '';

  in {
    # Creating a FHSEnv shell
    devShells.${system}.default = fhs.env;

    packages.${system}.container = pkgs.dockerTools.buildImage {
      name = "yx-env";
      tag = "latest";
      # This (now) breaks reproducibility:
      #created = "now";
      # Contents to include in the image root
      # 3. Drop the symlinked tree into the container root
      copyToRoot = [
        fhsLayout
        usrInclude  # Provides /usr/include -> /bin/include
        pkgs.dockerTools.binSh
        pkgs.dockerTools.usrBinEnv
        pkgs.dockerTools.caCertificates
        pkgs.dockerTools.fakeNss
      ];

      config = {
        Cmd = [ "/bin/bash" ];
        Env = [
          "TZDIR=/share/zoneinfo"
          "LANG=en_US.UTF-8"
          "LANGUAGE=en_US:en"
          "LC_ALL=en_US.UTF-8"
          # Point to the locale archive generated by glibcLocales
          "LOCALE_ARCHIVE=/lib/locale/locale-archive"
          "BB_ENV_PASSTHROUGH_ADDITIONS=$BB_ENV_PASSTHROUGH_ADDITIONS LOCALE_ARCHIVE"
          # 4. Standard Linux paths so the container knows where to look
          "LD_LIBRARY_PATH=/lib:/usr/lib"
          "PATH=/bin:/usr/bin"
        ];
      };
    };
  };
}

