#!/bin/bash

set -eo pipefail

usage_help ()
{
	echo ""
	echo "Usage: $yxenv_self <command> <profile> [extra-nix-packages] [extra-nix-cmd-options]"
	echo ""
	echo "  Commands:"
	echo "    - image - build a container image"
	echo "    - shell - start a nix devShell"
	echo ""
	echo "  Profiles i.e.:"
	echo "    - minimal - use a minimal set of packages"
	echo "    - yocto - use a set of packages ready for default Yocto builds"
	echo ""
	echo "  Extra Nix packages:"
	echo "    A list of extra Nix packages added to the selected profile."
	echo "    (i.e. \"hello cowsay\")"
	echo ""
	echo "  Extra 'nix' command options:"
	echo "    Extra options passed to final 'nix' command."
	echo "    (i.e. -L --rebuild ...)"
	echo ""
}

yxenv_self="$0"
yxenv_cmd="$1"
shift || true

yxenv_profile="${1:-}"
shift || true

yxenv_extend=
yxenv_impure=
yxenv_extra="${1:-}"
if [[ "$yxenv_extra" == -* ]]; then
	yxenv_extra=""
else
	if [[ -n "$CI" && -n "$yxenv_extra" ]]; then
		echo "ERROR: Extra packages are not allowed in CI"
		exit 1
	fi
	shift || true
fi

if [ -z "$yxenv_cmd" ]; then
	echo "Missing command!"
	usage_help
	exit 1
fi

case "$yxenv_cmd" in
help)
	usage_help
	;;

image|shell)
	if [ -z "$yxenv_profile" ]; then
		echo "Missing profile!"
		usage_help
		exit 1
	fi

	echo "Building environment with profile: $yxenv_profile"
	if [ -n "$yxenv_extra" ]; then
		yxenv_extend="_extra"
		yxenv_impure="--impure"
		echo "  - adding extra packages: ${yxenv_extra}"
	fi

	case "$yxenv_cmd" in
	image)
		echo "  - container image: ${yxenv_profile}${yxenv_extend}"
		exec env YXENV_EXTRA="${yxenv_extra}" YXENV_EXTEND="${yxenv_extend}" nix build .#${yxenv_profile} ${yxenv_impure} $@
		;;

	shell)
		echo "  - interactive shell: ${yxenv_profile}${yxenv_extend}"
		exec env YXENV_EXTRA="${yxenv_extra}" YXENV_EXTEND="${yxenv_extend}" nix develop .#${yxenv_profile} ${yxenv_impure} $@
		;;
	esac
	;;

*)
	echo "Unknown command: $yxenv_cmd"
	usage_help
	exit 1
	;;
esac
